<?php
include_once 'header.php'
?>
<link rel="stylesheet" href="PK007.css">

<h4>Packages > More Details </h4>
    <div class="row1">
        <div class="column1">
            <img src="LK94009488-11-E.webp" width="725" hight="350">
        </div>
        <div class="column2">
               <img src="download.jfif" width="220" hight="150">
               <img src="images (1).jfif" width="200" hight="100">
                <img src="Madu-River-2.jpg" width="280" hight="150">
        </div>
    </div>
    <div class="row1">
        <img src="800x750-44.jpg" width="500" hight="493">
    </div>

    <table class="button">
        <tr>
            <td id="mtd1">
                <input type="button" value="More Images" ><br> 
            </td>
        </tr>
    </table>

    <h2>Star Rating</h2>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star checked"></span>
    <span class="fa fa-star"></span>
    <span class="fa fa-star"></span>
    
    <table class="more">
        <tr>
            <td><h2>Package Details</h2><br><br>
                <p id="more"><br><br>
                    Pkg_ID: PK007<br>
                    Location: Madu River - Balapitiya<br>
                    Price: 5,000/=<br>
                    Duration: 1.5 hours<br>
                    No of People: 8 People<br><br><br>
                </p>
                <button><a href= "PlaceReservation.php">Place Reservation</a></button>
                <button>Save</button><br><br>
                <a href="FAQ.php"><button>FAQ</button></a><br>
                <br><br>
                <a href="https://goo.gl/maps/6hp6nm9deSv2Wvab8">
                    <img src="new-google-maps-icon-logo-263A01C734-seeklogo.com.png" width="300">
                </a>
            </td>
            <td id="mtd2">
                <h2>Hinerary</h2><br><br>
                        <p id="more"><br>1. You will be picked up from your<br> hotel and driven to Benthota.<br><br></p>
                        <br><br>
                       <p id="more"><br>2. Start a memorable boat <br>ride in Madu river and experience<br>
                         an exciting ride through <br>the mangrove caves to <br>
                         visit some beautiful riverside attractions.<br><br></p><br><br>
                        <p id="more"><br>3. You will be able to enjoy <br>fish therapy and visit <br>
                        a cinnamon island & island temple<br> during this boat tour.<br><br></p><br><br>
                        <p id="more"><br>4. You will be taken<br> back to your hotel<br><br></p><br><br>

                        </p>
                    </li>
                </ol>

            </td>
        </tr>
    </table>
    <br><br><br><br><br><br><br><br>


<?php
include_once 'footer.php'
?>
